config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  root "admin/projects#index"
  namespace :admin do
    resources :projects, except: [:show]
    resources :newsletters, only: [:index, :destroy, :new, :create]
    resources :project_contact_messages, only: [:index, :destroy]
    resources :contact_messages, only: [:index, :destroy]
    resources :admins, only: [:index, :create, :update, :destroy]
  end

  namespace :api, format: 'json' do
    get "/projects", to: "projects#index"
    post "/newsletter", to: "newsletters#create"
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, :email, presence: true
  
  default_scope { order(created_at: :asc) }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/newsletter.rb
# == Schema Information
#
# Table name: newsletters
#
#  id         :bigint           not null, primary key
#  email      :string
#  accepted   :boolean
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Newsletter < ApplicationRecord
    validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id           :bigint           not null, primary key
#  image        :string
#  title        :string
#  description  :text
#  category     :string
#  site_url     :string
#  technologies :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#
class Project < ApplicationRecord
    mount_uploader :image, ImageUploader

    validates :title, presence: true, uniqueness: true, length: { minimum: 3 }
    validates :description, presence: true, length: { minimum: 10 }
    validates :category, :site_url, :technologies, presence: true
    
end

app/controllers/admin/admins_controller.rb
class Admin::AdminsController < Admin::BaseController
    before_action :authenticate_superadmin!, only: [:create, :update, :destroy]

    def index
        @admins = Admin.all
        if current_admin.is_superadmin
            @admin = params[:admin_id].nil? ? Admin.new : Admin.find(params[:admin_id])
        end
    end

    def create
        @admin = Admin.new(admin_params)
        respond_to do |format|
            if @admin.save
                format.html{ redirect_to admin_admins_path, notice: "Administrator uspješno kreiran" }
            else
                format.html{ redirect_to admin_admins_path, alert: @admin.errors.full_messages.join(", ") }
            end
        end
    end

    def update
        @admin = Admin.find(params[:id])
        respond_to do |format|
            if @admin.update(admin_params)
                format.html{ redirect_to admin_admins_path, notice: "Administrator uspješno uređen" }
            else
                format.html{ redirect_to admin_admins_path, alert: @admin.errors.full_messages.join(", ") }
            end
        end
    end

    def destroy
        @admin = Admin.find(params[:id])
        respond_to do |format|
            if @admin.destroy
                format.html{ redirect_to admin_admins_path, notice: "Administrator uspješno obrisan" }
            else
                format.html{ redirect_to admin_admins_path, alert: @admin.errors.full_messages.join(", ") }
            end
        end
    end

    private

    def admin_params
        params.require(:admin).permit(:email, :password, :password_confirmation, :is_superadmin, :first_name, :last_name )
    end

    def authenticate_superadmin!
        unless current_admin.is_superadmin
            redirect_to root_path
        end
    end

end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
    before_action :authenticate_admin!

    layout "admin"
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController

    def index
        @projects = Project.all
        @project = params[:project_id].nil? ? Project.new : Project.find(params[:project_id])
    end

    def create
        @project = Project.new(project_params)
        respond_to do |format|
            if @project.save
                format.html{ redirect_to admin_projects_path, notice: "Projekt uspješno kreiran" }
            else
                format.html{ redirect_to admin_projects_path, alert: @project.errors.full_messages.join(", ") }
            end
        end
    end

    def update
        @project = Project.find(params[:id])
        respond_to do |format|
            if @project.update(project_params)
                format.html{ redirect_to admin_projects_path, notice: "Projekt uspješno uređen" }
            else
                format.html{ redirect_to admin_projects_path, alert: @project.errors.full_messages.join(", ") }
            end
        end
    end

    def destroy
        @project = Project.find(params[:id])
        respond_to do |format|
            if @project.destroy
                format.html{ redirect_to admin_projects_path, notice: "Projekt uspješno obrisan" }
            else
                format.html{ redirect_to admin_projects_path, alert: @project.errors.full_messages.join(", ") }
            end
        end
    end

    private

    def project_params
        params.require(:project).permit(:image, :title, :description, :category, :site_url ,:technologies)
    end
end

app/controllers/api/newsletters_controller.rb
class Api::NewslettersController < ApplicationController
    skip_before_action :verify_authenticity_token

    def create
        newsletter = Newsletter.new(newsletter_params)
        if newsletter.save
            render json: { message: 'Uspješno ste se pretplatili na newsletter' }, status: :ok
        else
            render json: { errors: newsletter.errors.full_messages.join(',') }, status: 422
        end

    end

    private

    def newsletter_params
        params.require(:newsletter).permit(:email)
    end

end

app/controllers/api/projects_controller.rb
class Api::ProjectsController < ApplicationController

    def index
        @projects = Project.all

        respond_to do |format|
            format.json
        end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


end

app/helpers/admin/admins_helper.rb
module Admin::AdminsHelper
end

app/helpers/admin/projects_helper.rb
module Admin::ProjectsHelper
end

app/helpers/api/newsletters_helper.rb
module Api::NewslettersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/admin/admins/index.html.erb
<% content_for :title, "Administratori" %>

<h2>Administratori</h2>
<table>
    <tr class="table-heading">
        <th>Ime</th>
        <th>Prezime</th>
        <th>Email</th>
        <th>Superadmin</th>
        <% if current_admin.is_superadmin %>
            <th>Akcije</th>
        <% end %>
    </tr>
    <% @admins.each do |admin| %>
        <tr>
            <td><%= admin.first_name %></td>
            <td><%= admin.last_name %></td>
            <td><%= admin.email %></td>
            <td><%= admin.is_superadmin ? "Da" : "Ne" %></td>
            <% if current_admin.is_superadmin %>
                <td>
                    <%= link_to "Uredi", admin_admins_path(admin_id: admin.id) %>
                    <%= link_to "Obriši", admin_admin_path(admin), method: :delete, data:{confirm: "Jeste li sigurni?"} %>
                </td>
            <% end %>
        </tr>
    <% end %>
</table>

<% if current_admin.is_superadmin %>
    <%= form_for [:admin, @admin], data: { turbo:false } do |form| %>
        <fieldset>
            <legend><%= @admin.persisted? ? "Uredi administratora" : "Dodaj novog administratora" %></legend>
            <div class="input-group vertical">
                <%= form.label :first_name, "Ime", class: "form-label"%>
                <%= form.text_field :first_name, class: "input"%>
            </div>

            <div class="input-group vertical">
                <%= form.label :last_name, "Prezime", class: "form-label"%>
                <%= form.text_field :last_name, class: "input"%>
            </div>

            <div class="input-group vertical">
                <%= form.label :email, "Email", class: "form-label"%>
                <%= form.email_field :email, class: "input"%>
            </div>

            <div class="input-group vertical">
                <%= form.label :is_superadmin, "Superadmin?", class: "form-label"%>
                <%= form.check_box :is_superadmin, {class: "checkbox_input"}, "true", "false"%>
            </div>

            <div class="input-group vertical">
                <%= form.label :password, "Lozinka", class: "form-label"%>
                <%= form.text_field :password, class: "input"%>
            </div>

            <%= form.submit @admin.persisted? ? "Uredi" : "Spremi", class: "submit"%>
        </fieldset>
    <% end %>
<% end %>

app/views/admin/projects/index.html.erb
<% content_for :title, "Projekti" %>
<h2>Projekti</h2>
<table>
    <tr class="table-heading">
        <th>Naziv projekta</th>
        <th>Opis</th>
        <th>Kategorija</th>
        <th>URL stranice</th>
        <th>Tehnologije</th>
        <th>Slika</th>
        <th>Akcije</th>
    </tr>
    <% @projects.each do |project| %>
        <tr>
            <td><%= project.title %></td>
            <td><%= project.description %></td>
            <td><%= project.category %></td>
            <td><%= project.site_url %></td>
            <td><%= project.technologies %></td>
            <td><%= image_tag project.image_url, height: "100px"%></td>
            <td>
                <%= link_to "Uredi", admin_projects_url(project_id: project.id) %>
                <%= link_to "Obriši", admin_project_path(project), :method => :delete, data: {confirm: "Jeste li sigurni?"} %>
            </td>
        </tr>
    <% end %>
</table>

<%= form_for [:admin, @project], data: { turbo:false } do |form| %>
    <h2><%= @project.persisted? ? "Uredi projekt" : "Dodaj novi projekt" %></h2>

    <fieldset>
    <div class="input-group vertical">
        <%= form.label :title, "Naziv projekta", class: "form-label"%>
        <%= form.text_field :title, class: "input"%>
    </div>

    <div class="input-group vertical">
        <%= form.label :description, "Opis", class: "form-label"%>
        <%= form.text_field :description, class: "input-area"%>
    </div>
    <div class="input-group vertical">
        <%= form.label :category, "Kategorija", class: "form-label"%>
        <%= form.select :category, ["Web dizajn", "Web stranica", "Web shop", "Web aplikacija"] %>
    </div>

    <div class="input-group vertical">
        <%= form.label :site_url, "URL stranice", class: "form-label"%>
        <%= form.text_field :site_url, class: "checkbox_input"%>
    </div>

    <div class="input-group vertical">
        <%= form.label :technologies, "Tehnologije", class: "form-label"%>
        <%= form.text_field :technologies, class: "input-area"%>
    </div>

    <div class="input-group horizontal">
        <%= form.label :image, "Slika", class: "form-label"%>
        <%= form.file_field :image, prompt: "Učitaj sliku" %>
    </div>
    <% if @project.persisted? %>
        <%= image_tag @project.image_url, height: "50px"%>
    <% end %>
    
    <div><%= form.submit @project.persisted? ? "Uredi" : "Spremi", class: "submit input-group"%></div>
    </fieldset>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <%= content_for?(:title) ? "Cubes Dev | " + yield(:title) : "Cubes Dev" %>
    </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mini.css/3.0.1/mini-default.min.css">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/admin/navigation" %>
    
    <%= yield %>

    <%= render "layouts/admin/notification" %>
  </body>
</html>

app/views/layouts/admin/_navigation.html.erb
<h1>Cubes Dev - Admin</h1>
<nav>
    <ul>
        <h3><b>Pozdrav <%= current_admin.first_name%>!</b></h3>
        <b><%= link_to "Odjavi se", destroy_admin_session_path, :method => :delete %></b>
        <br><br>

        <li><%= link_to "Administratori", admin_admins_path %></li>
        <li><%= link_to "Projekti", admin_projects_path %></li>
    </ul>
</nav>

app/views/layouts/admin/_notification.html.erb
<% flash.each do |type, msg| %>
  <div class="notification">
    <span class="toast"><span id="close"><b>×</b> </span><%= msg %></span>
  </div>
<% end %>


<script>
 document.addEventListener("turbo:load", function() {
   const close = document.getElementById("close");
   if (close) {
     close.addEventListener("click", function() {
       this.parentElement.style.transition = "all 0.5s ease";
       this.parentElement.style.display = "none";
     });
   }
 });
</script>

<style>
  #close{
    font-size: 25px;
    font-weight: bold;
    cursor: pointer;
    transition: 0.3s;
  }
  span.toast{
    font-size: 25px;
  }
  #close:hover{
    color: red;
  }

</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CubesBackend</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mini.css/3.0.1/mini-default.min.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>